# Generated by Django 5.0.7 on 2024-09-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='volumn',
        ),
    ]
